---
# task/prerequisites file for import_vault_root_ca
- name: "Install dependencies"
  ansible.builtin.include_role:
    name: ednz_cloud.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ import_vault_root_ca_packages }}"

- name: "Create directory {{ import_vault_root_ca_cert_dir }}"
  ansible.builtin.file:
    path: "{{ import_vault_root_ca_cert_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
